version: 2.1
workflows:
  env-vars:
    jobs:
      - build:
          context: microservice
jobs:
  build:
    working_directory: /udagram-microservices
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              --upgrade pip \
              docker-compose==1.15.0 \
              awscli==1.11.76
      - run:
          name: compose convert
          command: |
            SET COMPOSE_CONVERT_WINDOWS_PATHS=1
      - run:
          name: compose tls version
          command: |
            set COMPOSE_TLS_VERSION=TLSv1_2
      - run:
          name: docker build
          command: |
            docker-compose build
      - run:
          name: docker ps
          command: |
            docker ps
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag udagram-api-user $DOCKER_HUB_USER_ID/udagram-api-user:v1
            docker push $DOCKER_HUB_USER_ID/udagram-api-user:v1
            docker tag udagram-api-feed $DOCKER_HUB_USER_ID/udagram-api-feed:v1
            docker push $DOCKER_HUB_USER_ID/udagram-api-feed:v1
            docker tag udagram-frontend $DOCKER_HUB_USER_ID/udagram-frontend:v1
            docker tag udagram-frontend $DOCKER_HUB_USER_ID/udagram-frontend:local
            docker push $DOCKER_HUB_USER_ID/udagram-frontend:v1
            docker push $DOCKER_HUB_USER_ID/udagram-frontend:local
            docker tag udagram-reverseproxy $DOCKER_HUB_USER_ID/udagram-reverseproxy:v1
            docker push $DOCKER_HUB_USER_ID/udagram-reverseproxy:v1
